/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AlbumSlugRouteImport } from './routes/album.$slug'
import { Route as TripSlugRouteImport } from './routes/trip.$slug'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AuthAuth0CallbackRouteImport } from './routes/auth.auth0.callback'
import { Route as TripSlugImagesRouteImport } from './routes/trip.$slug.images'
import { Route as TripSlugProcessingRouteImport } from './routes/trip.$slug.processing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumSlugRoute = AlbumSlugRouteImport.update({
  id: '/album/$slug',
  path: '/album/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TripSlugRoute = TripSlugRouteImport.update({
  id: '/trip/$slug',
  path: '/trip/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuth0CallbackRoute = AuthAuth0CallbackRouteImport.update({
  id: '/auth/auth0/callback',
  path: '/auth/auth0/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TripSlugImagesRoute = TripSlugImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => TripSlugRoute,
} as any)
const TripSlugProcessingRoute = TripSlugProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => TripSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/trip/$slug': typeof TripSlugRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/auth/auth0/callback': typeof AuthAuth0CallbackRoute
  '/trip/$slug/images': typeof TripSlugImagesRoute
  '/trip/$slug/processing': typeof TripSlugProcessingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/trip/$slug': typeof TripSlugRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/auth/auth0/callback': typeof AuthAuth0CallbackRoute
  '/trip/$slug/images': typeof TripSlugImagesRoute
  '/trip/$slug/processing': typeof TripSlugProcessingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-trip': typeof CreateTripRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/verify': typeof VerifyRoute
  '/album/$slug': typeof AlbumSlugRoute
  '/trip/$slug': typeof TripSlugRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRoute
  '/auth/auth0/callback': typeof AuthAuth0CallbackRoute
  '/trip/$slug/images': typeof TripSlugImagesRoute
  '/trip/$slug/processing': typeof TripSlugProcessingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/create-trip'
    | '/dashboard'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upload'
    | '/verify'
    | '/album/$slug'
    | '/trip/$slug'
    | '/api/v1/$'
    | '/auth/auth0/callback'
    | '/trip/$slug/images'
    | '/trip/$slug/processing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/create-trip'
    | '/dashboard'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upload'
    | '/verify'
    | '/album/$slug'
    | '/trip/$slug'
    | '/api/v1/$'
    | '/auth/auth0/callback'
    | '/trip/$slug/images'
    | '/trip/$slug/processing'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/create-trip'
    | '/dashboard'
    | '/faq'
    | '/get-started'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/upload'
    | '/verify'
    | '/album/$slug'
    | '/trip/$slug'
    | '/api/v1/$'
    | '/auth/auth0/callback'
    | '/trip/$slug/images'
    | '/trip/$slug/processing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreateTripRoute: typeof CreateTripRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  VerifyRoute: typeof VerifyRoute
  AlbumSlugRoute: typeof AlbumSlugRoute
  TripSlugRoute: typeof TripSlugRouteWithChildren
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  AuthAuth0CallbackRoute: typeof AuthAuth0CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$slug': {
      id: '/album/$slug'
      path: '/album/$slug'
      fullPath: '/album/$slug'
      preLoaderRoute: typeof AlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$slug': {
      id: '/trip/$slug'
      path: '/trip/$slug'
      fullPath: '/trip/$slug'
      preLoaderRoute: typeof TripSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/auth0/callback': {
      id: '/auth/auth0/callback'
      path: '/auth/auth0/callback'
      fullPath: '/auth/auth0/callback'
      preLoaderRoute: typeof AuthAuth0CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$slug/images': {
      id: '/trip/$slug/images'
      path: '/images'
      fullPath: '/trip/$slug/images'
      preLoaderRoute: typeof TripSlugImagesRouteImport
      parentRoute: typeof TripSlugRoute
    }
    '/trip/$slug/processing': {
      id: '/trip/$slug/processing'
      path: '/processing'
      fullPath: '/trip/$slug/processing'
      preLoaderRoute: typeof TripSlugProcessingRouteImport
      parentRoute: typeof TripSlugRoute
    }
  }
}

interface TripSlugRouteChildren {
  TripSlugImagesRoute: typeof TripSlugImagesRoute
  TripSlugProcessingRoute: typeof TripSlugProcessingRoute
}

const TripSlugRouteChildren: TripSlugRouteChildren = {
  TripSlugImagesRoute: TripSlugImagesRoute,
  TripSlugProcessingRoute: TripSlugProcessingRoute,
}

const TripSlugRouteWithChildren = TripSlugRoute._addFileChildren(
  TripSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreateTripRoute: CreateTripRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  VerifyRoute: VerifyRoute,
  AlbumSlugRoute: AlbumSlugRoute,
  TripSlugRoute: TripSlugRouteWithChildren,
  ApiV1SplatRoute: ApiV1SplatRoute,
  AuthAuth0CallbackRoute: AuthAuth0CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
